[package]
name = "titso-core"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "*"
snafu = "*"
byteorder = "*"
arrayref = "*"
rand_core = "0.5"
serde = { version = "1", features = ["derive"] }
serde_cbor = "*"
gimli-permutation = "*"
gimli-hash = "0.1.5"
