[package]
name = "titso-web"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
titso-core = { path = "../core" }

wasm-bindgen = "*"
wee_alloc = "0.4"
js-sys = "*"
web-sys = { version = "0.3", features = [ "Document", "HtmlButtonElement", "HtmlTextAreaElement" ] }
kvdb-web = "*"
gloo = "*"
